// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obioha_VillaAPI.Data;

#nullable disable

namespace Obioha_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Obioha_VillaAPI.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Built_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Current_Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("No_Of_Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("No_Of_Toilets")
                        .HasColumnType("int");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<string>("Property_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Purchase_Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Purchased_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sitting_Rooms_No")
                        .HasColumnType("int");

                    b.Property<int>("Square_Feet")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Built_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1949),
                            Created_Date = new DateTime(2022, 10, 13, 22, 50, 14, 977, DateTimeKind.Local).AddTicks(1294),
                            Current_Cost = 190000m,
                            ImageUrl = "Manchester.jpg",
                            Name = "Manchester_One",
                            No_Of_Bedrooms = 3,
                            No_Of_Toilets = 2,
                            Occupancy = 4,
                            Property_Type = "End Terraced House",
                            Purchase_Cost = 125000m,
                            Purchased_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1994),
                            Purpose = "Buy to Let",
                            Sitting_Rooms_No = 2,
                            Square_Feet = 75,
                            Updated_Date = new DateTime(2022, 10, 13, 22, 50, 14, 977, DateTimeKind.Local).AddTicks(1365)
                        },
                        new
                        {
                            Id = 2,
                            Built_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1969),
                            Created_Date = new DateTime(2022, 10, 13, 22, 50, 14, 977, DateTimeKind.Local).AddTicks(1368),
                            Current_Cost = 132000m,
                            ImageUrl = "Derby.jpg",
                            Name = "Derby_One",
                            No_Of_Bedrooms = 2,
                            No_Of_Toilets = 1,
                            Occupancy = 1,
                            Property_Type = "End Terraced House",
                            Purchase_Cost = 121500m,
                            Purchased_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1982),
                            Purpose = "Buy to Let",
                            Sitting_Rooms_No = 2,
                            Square_Feet = 75,
                            Updated_Date = new DateTime(2022, 10, 13, 22, 50, 14, 977, DateTimeKind.Local).AddTicks(1370)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
